#!/bin/bash -e
VER=$1
BUILD_TYPE=${2-Release}

printf "Compiling Zeek...\n"
URL=https://download.zeek.org/zeek-${VER}.tar.gz
printf "Zeek's download URL %s\n" ${URL}

# Check Zeek archive existance
cd /usr/src
if test ! -e zeek-${VER}.tar.gz; then
    curl -fsLO ${URL}
fi
# Check that curl didnt return an error
if test $? -eq 22; then
    printf "There was an error while downloading Zeek... Exiting.\n"
    exit 1
fi
# Remove previous duplicated/homonymes and extract Zeeks data
tar --recursive-unlink -zxf zeek-${VER}.tar.gz
cd zeek-${VER}
# configure reference https://github.com/zeek/zeek/blob/master/configure
./configure --prefix=/usr/local/zeek-${VER} --generator=Ninja --build-type="${BUILD_TYPE}" --disable-broker-tests --disable-btest --disable-btest-pcaps --disable-cpp-tests --disable-javascript
ninja -C /usr/src/zeek-${VER}/build install