#!/bin/bash -e
ZEEK=$1
VER=$2
BUILD_TYPE=${3-Release}

URL=https://download.zeek.org/${ZEEK}-${VER}.tar.gz

echo VER is $VER
echo URL is $URL

cd /usr/src/
if [ ! -e ${ZEEK}-${VER}.tar.gz ] ; then 
    wget -c $URL
fi
if [ ! -d ${ZEEK}-${VER} ]; then
    tar xvzf ${ZEEK}-${VER}.tar.gz
fi
cd ${ZEEK}-${VER}
# configure reference https://github.com/zeek/zeek/blob/master/configure
./configure --prefix=/usr/local/${ZEEK}-${VER} --generator=Ninja --build-type="${BUILD_TYPE}" --disable-btest-pcaps --disable-broker-tests --disable-cpp-tests
# make reference: https://github.com/zeek/zeek/blob/master/docker/Makefile
ninja -C /usr/src/${ZEEK}-${VER}/build install
